# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ac4d4bc1b8def6ffa74c7fa2cd529df"
name = "product-counter-app"
handle = "product-counter-app-3"
application_url = "https://chris-programmers-bryant-climate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mobi-cast-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://chris-programmers-bryant-climate.trycloudflare.com/auth/callback",
  "https://chris-programmers-bryant-climate.trycloudflare.com/auth/shopify/callback",
  "https://chris-programmers-bryant-climate.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
